# Generated by Django 3.1.7 on 2021-04-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=15)),
                ('password', models.CharField(max_length=10)),
                ('repassword', models.CharField(max_length=10)),
            ],
        ),
    ]
